### ISSUE TITLE
Not working with https 

### ISSUE THREAD

**Issue by AnotherqwertyUser** [w8tcha/ripper#6]
I had to change the login page to use https, but most image hosts seem to have switched from http to https as well. Is there a newer version of this somewhere? Or is there an installer for your newest version?

**Comment by w8tcha** [comment]
Be aware that this program is no longer in development. There will be no more new versions!

**Comment by AnotherqwertyUser** [comment]
So, just like the official viperripper.
I assumed that since the last check in was 2 months ago, it was in development still

**Comment by w8tcha** [comment]
The project is dead since over 4 years. After it was replaced by the other official ripper

**Comment by AnotherqwertyUser** [comment]
Thanks
